### ISSUE TITLE
[question] Config files from two different profiles with CMakeDeps and CMakeToolchain

### ISSUE THREAD

**Issue by jjcasmar** [conan-io/conan#12990]
### What is your question?

I have been doing some testing with CMakeDeps and CMakeToolchain generators. My conanfile.py is the following:

```
from conan import ConanFile
from conan.tools.cmake import CMakeDeps, CMakeToolchain, cmake_layout


class HDF5Test(ConanFile):
    settings = "os", "arch", "compiler", "build_type"

    def requirements(self):
        self.requires("highfive/2.6.2")

    def generate(self):
        cmake = CMakeDeps(self)
        cmake.generate()

        toolchain = CMakeToolchain(self)
        toolchain.variables["CMAKE_MAP_IMPORTED_CONFIG_DEBUG"] = "Release"
        toolchain.generate()

    def layout(self):
        cmake_layout(self)

```

When I run `conan install . --build=missing`, it writes several files (FooConfig.cmake files and conan_toolchain.cmake) under build/generators.

However, if I have another profile and I rerun `conan install . --build=missing -pr=myprofile`, with some non default options, such as another compiler for example, it just overwrites the files in build/generators. 

How could I generate my toolchain and Config files under another folder? 

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Hi @jjcasmar 

Thanks for your question.

Quick questions: What version of conan are you using and what compiler and build system (ninja, VS) are you using? Because that affects:
- VS is a multi-config generator it is expected that both debug and release will have the same configuration, same project, same preset-configure, same conan_toolchain.cmake, just 2 different builds
- Others like gcc/makefiles are single config generators, and are expected to have their own configure, their own toolchain and presets. There was a bug regarding this, that was solved in latest Conan, if you haven't upgraded please do and check again.

**Comment by jjcasmar** [comment]
So right now I am testing with Ninja and trying to have my dependencies built with different versions of gcc or clang. 
I am using conan 1.56

**Comment by memsharded** [comment]
Yes, Conan 1.57 is the one containing the fix, please upgrade and try again and let us know.

**Comment by jjcasmar** [comment]
Testing with 1.57. That doesn't solve that the Config file are overwrriten

**Comment by memsharded** [comment]
Oh, I see, you mean when changing compiler, for example.
This follows more or less the same default as CMake, the generated folder variability, by default is Debug/Release mostly. You should see different folders for those.
If you want extra variability for others you should define ``tools.cmake.cmake_layout:build_folder_vars`` config, something like:
```
[conf]
tools.cmake.cmake_layout:build_folder_vars=["settings.compiler", "settings.compiler.version"]
```

**Comment by jjcasmar** [comment]
Where do I define that? Can it be defined in a conanfile.py? But yeah, I want different Config packages depending on the used profile, as they can be generating different packages.

**Comment by memsharded** [comment]
In the profile files as above, or in command line with ``-c ....``

**Comment by jjcasmar** [comment]
Is it possible to define it in the conanfile somehow? So that with any profile it generates the Config files in different places

**Comment by memsharded** [comment]
Not in the recipes at the moment, but you can also put it in the ``global.conf`` global configuration (in your cache), and it will apply always.

**Comment by memsharded** [comment]
Closing this ticket as outdated, and not an issue anymore in Conan 2.
But please let us know if otherwise, re-open or create a new ticket for any further question or issue. Thanks for the feedback!
