### ISSUE TITLE
[bug] [conan2] conan list output is missing the "info"/"settings" part of the package.

### ISSUE THREAD

**Issue by hpe-ykoehler** [conan-io/conan#13026]
### Environment details

* Operating System+version: Ubuntu 22.04LTS
* Compiler+version: gcc+11.3.0
* Conan version: 2.0.0b8
* Python version: 3.10.6

### Steps to reproduce

$ conan install --requires zlib/1.2.11 --build=missing
$ conan list zlib/1.2.11:*#* --format=json

The output I get then from last command is :
```
{
    "Local Cache": {
        "zlib/1.2.11": {
            "revisions": {
                "ffa77daf83a57094149707928bdce823": {
                    "timestamp": "2022-11-02 13:46:53 UTC",
                    "packages": {
                        "b647c43bfefae3f830561ca202b6cfd935b56205": {
                            "revisions": {
                                "f4e9ede65dd5374480127765ee413f91": {
                                    "timestamp": "2023-02-01 19:46:46 UTC"
                                }
                            }
                        }
                    }
                }
            }
        }
    }
}
```

The documentation at https://docs.conan.io/en/2.0/reference/commands/list.html indicated I should be seeing a lot more data:

```
{
  "Local Cache": {
    "zli/1.0.0": {
      "revisions": {
        "b58eeddfe2fd25ac3a105f72836b3360": {
          "timestamp": "2023-01-10 16:30:27 UTC",
          "packages": {
            "9a4eb3c8701508aa9458b1a73d0633783ecc2270": {
              "revisions": {
                "d9b1e9044ee265092e81db7028ae10e0": {
                  "timestamp": "2023-01-10 22:45:49 UTC"
                }
              },
              "info": {
                "settings": {
                   "os": "Linux"
                }
              }
            },
            "ebec3dc6d7f6b907b3ada0c3d3cdc83613a2b715": {
              "revisions": {
                "d9b1e9044ee265092e81db7028ae10e0": {
                  "timestamp": "2023-01-10 22:45:49 UTC"
                }
              },
              "info": {
                "settings": {
                  "os": "Windows"
                }
              }
            }
          }
        }
      }
    }
  }
}
```

Also if I ask the same for a given remote the data I received is even more so limited:

```
$ conan remote list
conancenter: https://center.conan.io [Verify SSL: True, Enabled: True]
conanv2: https://conanv2beta.jfrog.io/artifactory/api/conan/conan [Verify SSL: True, Enabled: True]
```

```
$ conan list zlib/1.2.11:*#* -r conancenter --format=json
{
    "conancenter": {
        "zlib/1.2.11": {
            "revisions": {
                "ffa77daf83a57094149707928bdce823": {
                    "timestamp": "2022-11-02 13:46:53 UTC"
                }
            }
        }
    }
}
$ conan list zlib/1.2.11:*#* -r conanv2 --format=json
{
    "conanv2": {
        "error": "500: org.jfrog.repomd.conan.exceptions.ConanInfoException: Missing section in conaninfo.txt. [Remote: conanv2]"
    }
}
```

**Comment by memsharded** [comment]
Hi @hpe-ykoehler 

Would you please upgrade to latest beta? https://github.com/conan-io/conan/releases/tag/2.0.0-beta9. We are still polishing some details of the patterns, and this has changed. It is also very likely that the docs are outdated, we will update them soon.

Also yes, we are aware of some Artifactory bug, reported in https://github.com/conan-io/conan/issues/12418 and https://github.com/conan-io/conan/issues/11370. It is already fixed in Artifactory in the code, and it is planned to be released soon. Please keep tuned to Artifactory releases and the tickets, we will report once this is released.

**Comment by hpe-ykoehler** [comment]
Hi,

Yeah sure, nice will upgrade to conan2.0.0 b9, and try it out.

Note that the issue I reported with remotes, I also had them on my oss-ce 7.56 Artifactory server.

**Comment by memsharded** [comment]
Yes, yes, that would be a different issue related to the server side: https://github.com/conan-io/conan/issues/12418

The fix is already there in Artifactory code, it will be included in some of the next Artifactory releases, please track that ticket for following up.

So if upgrading to 2.0.0-b9 works with the cache, then we could close this ticket as solved, and follow the other one for the server, please let us know.

**Comment by hpe-ykoehler** [comment]
ok so the fix is not in 7.56 either, ok will monitor for a fix then.

Thanks

**Comment by memsharded** [comment]
7.56? https://www.jfrog.com/confluence/display/JFROG/Artifactory+Release+Notes latest in 7.52

It seems the fix is released in 7.52: https://www.jfrog.com/confluence/display/JFROG/Artifactory+Release+Notes#ArtifactoryReleaseNotes-Artifactory7.52

**Comment by hpe-ykoehler** [comment]
Hmm, the ticket you referred me to indicate that this was fix in 7.52 of artifactory but I am having the problem on my server and I am running 7.56 (OSS-CE)

Therefore I need to reopen this since I am still not seeing the package info properly.  Using 2.0.0b9 and 7.56 for package on my remote, which I uploaded using same conan verison.

**Comment by memsharded** [comment]
7.56 is not released yet, please check https://www.jfrog.com/confluence/display/JFROG/Artifactory+Release+Notes

If you download latest CE from our download page you will get 7.49. 

7.52 so far is released only in cloud. I don't know what could be happening, maybe you mean 7.46?

**Comment by hpe-ykoehler** [comment]
Hmm, in the log of my container I see:
```
    ] [main                ] [] - Router (jfrou) service initialization started. Version: 7.56.0-1 Revision: b38308e786e218cb58aa9df2a12f3007b67156b0 PID: 3933 Home: /opt/jfrog/artifactory
```

This is my image

```
6e5dff2a0065   docker.bintray.io/jfrog/artifactory-cpp-ce:latest                           "/entrypoint-artifac…"   3 days ago       Up 3 days                 0.0.0.0:8081-8082->8081-8082/tcp   artifactory
```

**Comment by memsharded** [comment]
That might be an internal version of the Router component, which might be ahead of Artifactory. 
Latest CE version is 7.49

**Comment by memsharded** [comment]
Closing this ticket, it seems it is fixed, and the server side issue should be better reported to https://github.com/conan-io/conan/issues/11370 if necessary (waiting for the final 7.52 to be available, now only on SaaS)
