### ISSUE TITLE
default_options don't have an effect on dependencies from build_requires

### ISSUE THREAD

**Issue by ntff** [conan-io/conan#1411]
I have two packages.

first one:

from conans import ConanFile
```python
class package(ConanFile):
    name            = "first"
    version         = "0.0.0"
    description     = ""
    url             = "http://gitlab.com"
    options         = {"coverage": [True, False]}
    default_options = "coverage=False"

    def build(self):
        pass
```

I export it to local repo with:
```shell
user@host:~$ conan export user/stream
```

and build with:
```shell
user@host:~$ conan install first/0.0.0@user/stream --build first
```

second project:
```python
from conans import ConanFile

class package(ConanFile):
    name            = "second"
    version         = "0.0.0"
    description     = ""
    default_options = "first:coverage=True"
    requires        = "first/0.0.0@user/stream"
#    build_requires  = "first/0.0.0@user/stream"

    def build(self):
        pass
```

I build it in workspace, without exporting even to local repo:
```shell
user@host:~$ conan install
Requirements
    first/0.0.0@user/stream from local
Packages
    first/0.0.0@user/stream:7c60645c9b3774249d0628b89743ef9375228263

WARN: Can't find a 'first/0.0.0@user/stream' package for the specified options and settings:
- Settings: 
- Options: coverage=True

ERROR: Missing prebuilt package for 'first/0.0.0@user/stream'
Try to build it from sources with "--build first"
Or read "http://docs.conan.io/en/latest/faq/troubleshooting.html#error-missing-prebuilt-package"
```

I think it's correct. My first package default option was coverage=False.

Now I comment "requires" line in the second project and uncomment "build_requires":
```python
from conans import ConanFile

class package(ConanFile):
    name            = "second"
    version         = "0.0.0"
    description     = ""
    default_options = "first:coverage=True"
#    requires        = "first/0.0.0@user/stream"
    build_requires  = "first/0.0.0@user/stream"

    def build(self):
        pass
```

Again, I build it in-workspace:
```shell
user@host:~$ conan install
Requirements
Packages

: Build requires: [first/0.0.0@user/stream]
Installing build requires: [first/0.0.0@user/stream]
Requirements
    first/0.0.0@user/stream from local
Packages
    first/0.0.0@user/stream:5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9

first/0.0.0@user/stream: Already installed!
Installed build requires: [first/0.0.0@user/stream]
PROJECT: Generated txt created conanbuildinfo.txt
PROJECT: Generated conaninfo.txt
```
I didn't run that suggested command from the last build, so I don't have first package built with coverage=True in repo. But still, command succeeds.

I think, this is wrong!

Also, I think it's important that "default_options" affected dependencies from "build_requires" should not appear in conaninfo.txt, i.e. will not be a part of matching mechanism, same as for build_requires (i.e. appear if affect requires and not if for build_requires, but default_options is a single list).

tested for 0.24.0

**Comment by memsharded** [comment]
I have been having a look into this, running some tests.
Indeed, the ``build_requires`` don't get options from the conanfile, their options can be only set from the profiles or command line. 

I see this is not very intuitive at first sight, and I don't know how to classify it. The thing is that ``build_requires`` are non existing when the dependency graph is computed, and are only relevant if some package require them to build from sources. In the process, the ``options`` that are not used when the dependency graph is computed are removed (so they don't appear in conaninfo.txt, as you pointed out). And it totally makes sense, because ``build_requires`` doesn't affect the package ID, and then, their options shouldn't be part of the package recipe, because such options can affect the package ID.

I will re-think it and see what could be done. In the meantime, the workaround is of course, put the ``build_requires`` options in profiles.

**Comment by memsharded** [comment]
The cleaner solution for this could be to define a new ``build_requires_options`` attribute. What do you think @lasote?

**Comment by ntff** [comment]
I think adding something like `build_requires_options` is a bad idea.
Doing so will make possible building package with different options, but with the same in-repo signature,
and, as a result, it will not be possible to say how exactly package was built.

**Comment by ntff** [comment]
My original idea was to use `default_options` to define options for packages in `build_requires` even without declaring in `options` (or `build_requires_options`) in the package defining `build_requires`:
```python
from conans import ConanFile

class package(ConanFile):
    name            = "second"
    version         = "0.0.0"
    description     = ""
    default_options = "first:coverage=True"
    build_requires  = "first/0.0.0@user/stream"

    def build(self):
        pass
```

**Comment by memsharded** [comment]
Build_requires don't affect the package signature by definition, it doesn't matter what options do you pass them. They also don't appear in conaninfo.txt files.

I think I didn't express myself properly, my ``build_requires_options`` aren't really options, are the values to be applied, so in essence is the same as ``default_options``. So yes, I think maybe I could extract values from ``default_options`` and use them, without needing to define a new attribute. Thanks for the suggestion, I will give it a try.

**Comment by lasote** [comment]
Yes, I think it's better If we could use `default_options` for both but without affecting the conaninfo.

**Comment by memsharded** [comment]
It was quite difficult, but it might be solved for next release, I have submitted a PR: https://github.com/conan-io/conan/pull/1445

This use case for the options unveiled some deficiencies on the current approach that required major changes. Lets see how it goes the review and if we don't break anything :)

**Comment by memsharded** [comment]
Fixed. Will be released in 0.25

**Comment by memsharded** [comment]
Released in 0.25

**Comment by Cyriuz** [comment]
I ran into a problem with this when building with host and build profiles. The `build_requires_options` seems to be initialized with the collected options from the host graph which means that options that are removed based on the build environment will still exist and cause `option 'x' doesn't exist`. The example for my case being `libpng/1.6.37: option 'neon' doesn't exist`

Is this just a bug or have I misunderstood something?
