### ISSUE TITLE
Define arbitrary CMake variables in package_info()

### ISSUE THREAD

**Issue by bilke** [conan-io/conan#221]
It would be cool if one could define additional CMake variables in the `package_info()`-method which will be available on a CMake project similar to e.g. `CONAN_packagename_ROOT`.

Example:

```python
def package_info(self):
    ...
    self.cpp_info.variables = ["SOME_VAR=SomeValue"]
```

Can the be accessed with `CONAN_packagename_SOME_VAR` in CMake.

**Comment by memsharded** [comment]
Sorry, I made a mistake, the commit was trying to reference #211.

**Comment by memsharded** [comment]
About this issue, I agree it could be interesting, but I am concerned about non cmake users. There are users consuming packages with the Visual or Xcode generators, and if the packages have something which is CMake only, that wouldn't work for them. I think that we should try our best to keep this: packages consuming shouldn't depend on a particular build system if possible. 

Maybe knowing a little bit more about your actual use cases of the feature could be useful.

**Comment by bilke** [comment]
My use case is the following: I create a package for [VTK](http://vtk.org) which itself uses CMake and creates a CMake-file during build which has to be included in a project using this package. The CMake-file sets some CMake variables and compiler flags and so on.

In my package of VTK (which includes the CMake-file) I would like to somehow set a variable which points to the created CMake-file (from VTK), e.g.:

```python
def package_info(self):
    ...
    self.cpp_info.variables = ["VTK_USE_FILE=%s/UseVTK.cmake" % package_install_dir]
```

Of course I do not know if something like `package_install_dir` even exists.

I completely agree with you that packages should work with all generators but not all package authors will be able to ensure that for their packages. I think it will not harm anything when there are also generator-specific features in the `conanfile`, maybe the CMake variables can be named `self.cpp_info.cmake_variables` to make it more clear.

**Comment by memsharded** [comment]
Thanks for your feedback. There is a ``self.package_folder`` variable that you can use in your conanfile ``package()`` method, but not currently in the ``package_info()`` (though this can be very easily added).

In any case, your above case could already be addressed in the consumer side very simply, doing something like:

```cmake
set(VTK_USE_FILE "${CONAN_VTK_ROOT}/UseVTK.cmake")
```

As a general design principle, I think it is better try to keep upstream dependencies as agnostic as possible about its consumers. In your approach, you are defining the cmake variable that the consumer should use. On the consumer side, using such variable to load the generated cmake will work, but will be kind of magic. I think that specyfing in the consumer such variable, is much more explicit, intuitive and clear. "The file I must use is in the Conan package folder, with that name."

Does this make sense? Does it solves your use case?

**Comment by bilke** [comment]
Thanks, completely makes sense! And it also solves my question.

One issue remains (at least for me looking just through CMake glasses): using conan in an existing project is an all or nothing decision in the sense that I have to use the conan specified CMake variables instead of CMake's `find_package()`-calls.

I will investigate this further, maybe I can set some variables with search locations for `find_package`-calls by using the conan installed locations (e.g. setting `Boost_ROOT` before calling `find_package(Boost)`). I will post my results here if this works out.

**Comment by memsharded** [comment]
No, not really (about the all or nothing decission). In fact, we have many packages that also rely on find_package() features, trying to be a transparent replacement to default FindPackages cmake files:

- A package can create auxiliary files, including, for example FindMyLib.cmake, which are included in the package recipe with the ``exports=...`` conanfile field.
- Typically, the implementation of the FindMyLib.cmake, is very straightforward, as the package layout is simple, and it features just one configuration. One of the main problems of find_package is that FindPackage.cmake files have to deal with different library locations depending on the OS and other factors, which in my opinion, easily fails.
- The path of the packages you depend on is front inserted in CMAKE_MODULES_PATH in the ``conanbuildinfo.cmake`` file. If you are overriding a default find_package, as FindBoost, the conan package package FindBoost will be loaded, if ``conanbuildinfo.cmake``.
- So if you have a cmake project using find_package() you can easily opt-in, opt-out using conan for managing your dependencies, or using system ones by:

```cmake
if(EXISTS ${CMAKE_BINARY_DIR}/conanbuildinfo.cmake)
     include(${CMAKE_BINARY_DIR}/conanbuildinfo.cmake)
    conan_basic_setup()
    # OR, just to use find_packages without any other variables settings.
    set(CMAKE_MODULE_PATH ${CONAN_CMAKE_MODULE_PATH} ${CMAKE_MODULE_PATH})
endif()
```

This is not stable yet, but you can check for example: https://github.com/memsharded/conan-zmq/blob/master/FindZeroMQ.cmake.

This other example basically takes the original FindBoost and make some minor changes to provide conan support: https://github.com/lasote/conan-boost

It is true, that we tried first to use the default Find.cmake files and pass information to them, as the package root, as you intended. This can work sometimes, but it is somewhat error prone, as many find_packages() make a lot of assumptions about the package layout, which might not be true for conan packages. That is why we had better results by just providing and alternative Find.cmake file, which, to the eyes of the consumer is totally transparent.

Hope this gives some ideas an insights about current status of conan. Yes please, tell me about your progress, and other ideas an improvements welcome, cheers!

**Comment by mathieu** [comment]
I'll jump into this thread as my feature proposal is very close. We have begun to use the [other way of finding package](https://cmake.org/cmake/help/v3.5/manual/cmake-packages.7.html#id11) as we provide `packageConfig.cmake` and `packageConfigVersion.cmake` with our package libraries. `find_package(package)` will find these files and be happy if you set the CMAKE_PREFIX_PATH variable too : 
```cmake
if(EXISTS ${CMAKE_BINARY_DIR}/conanbuildinfo.cmake)
    include(${CMAKE_BINARY_DIR}/conanbuildinfo.cmake)
    conan_basic_setup()
    # OR, just to use find_packages without any other variables settings.
    set(CMAKE_MODULE_PATH ${CONAN_CMAKE_MODULE_PATH} ${CMAKE_MODULE_PATH})
    set(CMAKE_PREFIX_PATH ${CONAN_CMAKE_MODULE_PATH} ${CMAKE_PREFIX_PATH})
endif()
```

maybe we could enhance the documentation ?

**Comment by memsharded** [comment]
So, you are proposing that we also set the CMAKE_PREFIX_PATH variable inside the ``conan_basic_setup()``. Of course, not problem, that can be done. Or you are just suggesting to improve the documentation? ``conan_basic_setup()`` is actually split into smaller functions, maybe it makes sense to create one ``conan_cmake_modules()`` or the like, that basically sets those two CMake variables, right? This would be easy.

**Comment by memsharded** [comment]
Hi @bilke , @mathieu ,

The CMAKE_PREFIX_PATH was set in conanbuildinfo.cmake in a past release, so far it is working fine.
As @bilke pointed out above, the proposed approach was fine, and FindXXX.cmakes are being used, so I think this issue could be mostly closed. 
Please re-open or open a new issue if you think something else is needed. Thanks very much!
