### ISSUE TITLE
Error when running conan install in parallel

### ISSUE THREAD

**Issue by Hedanito** [conan-io/conan#2219]
I ran 2 instances of `conan install` in parallel (x86 and x64 with the same packages), and managed to get an error:

```
VulkanDocs/1.0.61@aurion/stable is locked by another concurrent conan process, wait...
If not the case, quit, and do 'conan remove VulkanDocs/1.0.61@aurion/stable -f'
ERROR: [WinError 32] The process cannot access the file because it is being used by another process: 'C:\\Users\\rick_\\.conan\\data\\VulkanDocs\\1.0.61\\aurion\\stable\\build\\5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9'

Couldn't remove folder, might be busy or open
Close any app using it, and retry
glslang/17.11.10@aurion/stable is locked by another concurrent conan process, wait...
If not the case, quit, and do 'conan remove glslang/17.11.10@aurion/stable -f'
```
It started by waiting nicely, and when one of the packages finished in the other process it threw an exception.

The VulkanDocs package then got skipped. So the file locking doesn't seem to be 100% foolproof yet. I'd also prefer it if it shut down instead of skipping the package, since it will probably lead to even more errors.

 * Platform: **Windows 10**
 * Build System: **CMake**
 * Compiler: **Visual Studio 15.5.2**
 * Conan version: **1.0.0b2**

**Comment by memsharded** [comment]
Yes, concurrency is complicated, and even if we have tried to stress the system a bit (like installing with >20 processes in parallel), it might happen that issues will still occur.

So the error is being produced in the locking of VulkanDocs? I am a bit confused about the error, ``gslang`` is just the next package in the dependency graph? Are you using the ``build_id()`` method in the recipe? Can you share the recipe with us? (if not possible in public, consider sending it privately, please)

There have been issues in the past in Windows with the Windows indexer. Have you tried to disable it for the conan local cache? Is it a problem that happens often, or did it happen just once? 

This might be a difficult issue to debug and fix, but lets try!

**Comment by Hedanito** [comment]
Yes, glslang is just the next package. I had 2 terminals open, both installing the same packages, but with different parameters. The error happened the moment the first process was done installing the VulkanDocs package and the second process noticed the lock was gone and tried to start installing.

I was running the following command for x86:
`conan install ..\.. -g cmake_multi -s build_type=Debug -s "arch=x86" -s "compiler=Visual Studio" -s "compiler.version=15"  -s compiler.runtime=MDd --build missing`

And pretty much the same for x64:
`conan install ..\.. -g cmake_multi -s build_type=Debug -s "arch=x86_64" -s "compiler=Visual Studio" -s "compiler.version=15"  -s compiler.runtime=MDd --build missing`

I've pushed all the package recipies to this repo: https://github.com/Hedanito/ConanPackagesForIssue2219. They all download their source from github, so you should be able to install them anywhere without problem. glslang also requires cmake to build.

And then you need to depend on them as follows:
```
requires = "glslang/17.11.10@x/y"
build_requires = "Catch/2.0.1@x/y", "VulkanDocs/1.0.61@x/y", "RapidJSON/1.1.1-beta1@x/y"
```

**Comment by memsharded** [comment]
Thanks very much for this info and putting together the repo.
Could you please detail the steps to reproduce? Are you first creating packages for VulkanDocs, RapidJson, including binaries first with ``conan create``? The ``--build missing`` is just in case, or being really used? And then, the installation of the binaries with ``conan install`` failed? Installing them from your local cache (already there) or downloading from a conan remote server?

I will be running some tests tomorrow, that would help to know. Thanks!

**Comment by Hedanito** [comment]
I don't have a server running right now, so all these packages are installed locally with `conan export`.
`--build missing` is used, although the error happened on the VulkanDocs package, which is a header only library, so I don't think that it's related. The only package that needs to be build is glslang.  This error happened while the cache was empty.

So to summarize:
 * Clear cache
 * Export packages to local cache
 * Run `conan install` multiple times on the same package requirements with different parameters
 * Repeat until an error occurs

I've only had the error happen once, so it's probably best to automate the test and let it run for a few hours, possibly with some lightweight packages and more than 2 installs at the same time.

**Comment by memsharded** [comment]
Thanks very much for the info. I have ran a few tests, but still not reproduced.

Regarding:

> There have been issues in the past in Windows with the Windows indexer. Have you tried to disable it for the conan local cache? Is it a problem that happens often, or did it happen just once?

Have you made sure you disabled indexing of the conan cache? This is a source of problems in Windows, and this could be well caused because of this. Access it in Start->Indexing Options-> Make sure the .conan folder under "Users" is not indexed.

**Comment by Hedanito** [comment]
Indexing was indeed turned on, although I can't say if that was the reason for the error.

**Comment by memsharded** [comment]
No, of course, it is impossible to know. But we have been reported and reproduced issues with the indexing on, disabling it really fixes things in conan in Windows, and could have originated yours.

**Comment by DoDoENT** [comment]
I am facing very similar, if not the same problem on my Jenkins server. My server has 4 executors that build different configurations of my code in parallel - one builds for Linux with Clang, another for Linux with GCC, 3rd for Android ARMv7, 4th for Android ARM64.

If I use the same Conan cache for all executors, then there is a race condition during installation of packages that match different configurations, for example, header-only version of boost. The problem is the following:

- all 4 executors start building code in parallel, each in a separate directory
- building starts with CMake build generation, which uses [cmake-conan](https://github.com/conan-io/cmake-conan) to invoke `conan install`
    - I find that much more practical than the manual invocation of `conan install`
- each of the 4 executors determines that header-only version of boost is missing and starts fetching it from `conan-center`
- the first executor finishes the download and extracts the package to cache and continues to compile step
- in the meantime, the second executor finishes the download, sees that extracted folder already exists, **deletes it** and extracts the newly downloaded package
- in the meantime, the first executor is in the middle of the compilation step and compilation fails because boost headers are missing because the second executor has deleted the package folder and still hasn't completed extracting of its version of the package

This is just one possible outcome of the race condition - the most probable one which happens almost always in my setup. Sometimes I also got CMake errors stating that imported package's include directory is empty (if the second executor deletes the package while the first one is still in CMake configuration phase), but I guess there are also other possible races that could happen.

My current workaround is to start with the clean Conan home folder for each executor on every build, however, this is extremely slow and puts a lot of pressure on my network, as every executor of every Jenkins node downloads all Conan dependencies every time. Another solution would be to have the separate Conan home folder for each executor on every node, but this would waste hundreds of gigabytes of disk space - something I cannot afford.

Therefore, I have a proposal for the solution for concurrent installation of Conan packages in the same home folder that should practically solve the described issue:

First, let's assume that package hash is unique and that concurrent installations of the same package will always result in the same end state, no matter the order of installations, provided that each installation is atomical.
    - I think this assumption is the basis for the whole Conan package manager, so we can rely on it

In order to ensure atomic installations of packages that will avoid the issue described above, we will first need to make a slight change in the organisation of the files within the Conan data folder. Namely, the location of `conan_package.tgz` should be **outside** of the folder with package hash. For example, we can introduce `compressed_package` folder next to the currently existing `package` folder in Conan's file system. The `compressed_package` should contain files with the names `package_hash1.tgz`, `package_hash2.tgz`, etc. This will make atomic package installation much easier, as `tgz` file will be outside of the `package/hash` folder, thus enabling both concurrent extraction and creation of the package, without interfering with the contents of `package/hash` folder.

Then, the Conan package installation procedure should be as follows:

1. Check if the requested package is already installed by checking that folder `package/hash` exists. If no, go to step 2. If yes, check if someone else is currently installing the same package by checking that file `package/hash.dirty` exists. If no, then the package is already installed and we are done. If yes, wait* until the file `package/hash.dirty` gets removed (with a reasonable timeout - if the timeout is reached, fail) and **then** we are done (we must wait for the concurrent process to finish the installation for us because we do not want to proceed to compilation while concurrent process may still be in the package extraction procedure - the compilation step would still observe missing headers and libraries). After we are done, check again that `package/hash` folder exists - if it exists, a concurrent process has successfully installed the package for us and we can continue to the build step. If it does not exist, a concurrent process has encountered an error in package extraction - something that should happen on rare occasions (corrupted package or corrupted download). Anyway, fail the installation in that case (the other process will also fail - see below).
2. Start downloading `conan_package.tgz` for the requested package to the temporary file **outside `package` folder** (python has methods for obtaining temporary files and folders in given folder using system calls that will guarantee unique file or folder even in highly parallel invocations). After the download completes, go to next step. If the download has failed, check if maybe someone else installed the package in the meantime as in step 1 and if not, then fail.
3. Check again if the requested package is already installed in the same way as in step 1. If `package/hash` still does not exist, go to next step.
4. Create folder `package/hash` and file `package/hash.dirty` (this is the first point of a race in the proposed solution unless there is a way to atomically create empty folder and file that I am not aware of) and start extracting the `tgz` file into folder `package/hash`. After extraction completes, simply remove the `package/hash.dirty` file and continue to the build step - the package has successfully been installed and we guaranteed that no concurrent process touched the folder during the procedure. If for some reason package extraction fails, **first** delete `package/hash` folder, **then** delete `package/hash.dirty` and then fail the installation - other processes that wait for file `package/hash.dirty` will also observe the failed installation and will fail as well (see step 1).

> *) I am not so much into python development, but a naive way for waiting for a file to be removed until some timeout is to regularly poll whether the file exists - it's terrible but it will work. Besides that, there are OS mechanisms to subscribe to file system events, but I really have no idea how to do that from python in a multi-platform way.

You can also create the lock files in step 3, before starting the download, to reduce the bandwidth, but my rationale is that the file download has much higher probability of failure than package extraction, so if multiple executors are downloading the same file in parallel, only one has to succeed. But of course, it would be best if that would be configurable.

I think this solution, although not perfect will pratically resolve the issues that I and @Hedanito described, as the only point of race is in creation of folder `package/hash` and file `package/hash.dirty` in the 4th step. The opportunity window for that to happen is very small, as opposed to current solution, where Conan first deletes the `package/hash`, then creates a new empty `package/hash` folder and `package/hash.dirty` file, then downloads the `conaninfo.txt` and `conanmanifest.txt`, then downloads `conan_package.tgz`, then extracts the package.**

> **) You can reproduce that with `conan 1.6.1` first ensuring that your `~/conan/data` does not have `boost` at all and then in two different terminals execute `conan install 'boost/1.67.0@conan/stable' -o header_only=True`. You will see that one terminal will install the package, while the other will wait on lock (it will also display a message that it is waiting on lock), but as soon as the lock is released, the other terminal will foolishly delete the package and start all over (both the download and extract), instead of just checking that another process has done its job and quit. Is there a reason for such a behaviour? Can it be disabled?

My guess is that similar solution can be also created for case when package is being built - we add lock on build folder (`build/hash.dirty`) and check for it before starting the build and skip the build if we waited - the same way as we waited here for package extraction. @memsharded, what do you think, can something like this be implemented rather soon?

**Comment by ferrucciobongianni** [comment]
Hello,
Has this issue been fixed? I have the very same problem (well described in the post above with the example of the two terminals)
Thanks

**Comment by memsharded** [comment]
Hi!

There are already locks over packages, they were implemented some time ago. It is possible that in some of recent refactors and changes to the way the packages are installed, some of these locks have been broken.

Lets have a look at it, thanks for reporting!

**Comment by ferrucciobongianni** [comment]
Hello @memsharded, did you manage to investigate this? This happens on version 1.7.3
Thanks

**Comment by jacobjiangwei** [comment]
hey, I don't think this was fixed.

We were running job on windows, two jobs in parallel, one was export and uploading, and another is installing.
One succeed and one failed.

Here is our log


12:38:46  + python conan_export_pkg.py --upload --os=windows
12:38:49  User of remote 'NetEaseConan' is already 'yunxin'
12:38:55  Exporting package recipe
12:38:55  WebRTC/4.0.0-358c5cb9@yunxin/testing: The stored package has not changed
12:38:55  WebRTC/4.0.0-358c5cb9@yunxin/testing: Exported revision: f58a06d080c5fe40555226d0add640dc
12:38:55  WebRTC/4.0.0-358c5cb9@yunxin/testing: Forced build from source
12:38:55  Packaging to 3475bd55b91ae904ac96fde0f106a136ab951a5e
12:38:56  Traceback (most recent call last):
12:38:56    File "shutil.py", line 393, in _rmtree_unsafe
12:38:56  PermissionError: [WinError 32] 另一个程序正在使用此文件，进程无法访问。: 'C:\\Users\\Public\\conan\\.conan\\data\\WebRTC\\4.0.0-358c5cb9\\yunxin\\testing\\dl\\pkg\\3475bd55b91ae904ac96fde0f106a136ab951a5e\\conan_package.tgz'
12:38:56  
12:38:56  During handling of the above exception, another exception occurred:
12:38:56  
12:38:56  Traceback (most recent call last):
12:38:56    File "conans\client\command.py", line 2115, in run
12:38:56    File "conans\client\command.py", line 1020, in export_pkg
12:38:56    File "conans\client\conan_api.py", line 94, in wrapper
12:38:56    File "conans\client\conan_api.py", line 452, in export_pkg
12:38:56    File "conans\client\cmd\export_pkg.py", line 51, in export_pkg
12:38:56    File "conans\paths\package_layouts\package_cache_layout.py", line 142, in package_remove
12:38:56    File "conans\util\files.py", line 266, in rmdir
12:38:56    File "shutil.py", line 500, in rmtree
12:38:56    File "shutil.py", line 395, in _rmtree_unsafe
12:38:56    File "conans\util\files.py", line 261, in _change_permissions
12:38:56  OSError: Cannot change permissions for C:\Users\Public\conan\.conan\data\WebRTC\4.0.0-358c5cb9\yunxin\testing\dl\pkg\3475bd55b91ae904ac96fde0f106a136ab951a5e\conan_package.tgz! Exception info: (<class 'PermissionError'>, PermissionError(13, '另一个程序正在使用此文件，进程无法访问。'), <traceback object at 0x03821738>)
12:38:56  
12:38:56  ERROR: Cannot change permissions for C:\Users\Public\conan\.conan\data\WebRTC\4.0.0-358c5cb9\yunxin\testing\dl\pkg\3475bd55b91ae904ac96fde0f106a136ab951a5e\conan_package.tgz! Exception info: (<class 'PermissionError'>, PermissionError(13, '另一个程序正在使用此文件，进程无法访问。'), <traceback object at 0x03821738>)
12:38:56  [Conan] channel:testing
12:38:56  [Conan] os:windows
12:38:56  [Conan] conan app checking......
12:38:56  [Conan] init completed!
12:38:56  [Conan] you can enjoy the package-manager now!
12:38:56  [Conan] version:4.0.0-358c5cb9
12:38:56  [Conan] Distribute channel set to testing
12:38:56  [Conan] Start uploading to Conan Server
12:38:56  Traceback (most recent call last):
12:38:56    File "conan_export_pkg.py", line 70, in <module>
12:38:56      subprocess.check_call(['conan', 'export-pkg', '.', "WebRTC/%s@yunxin/%s" % (version, options.channel), '-f', '-s', 'os=%s' % conan_os])
12:38:56    File "C:\Python27\lib\subprocess.py", line 190, in check_call
12:38:56      raise CalledProcessError(retcode, cmd)
12:38:56  subprocess.CalledProcessError: Command '['conan', 'export-pkg', '.', 'WebRTC/4.0.0-358c5cb9@yunxin/testing', '-f', '-s', 'os=Windows']' returned non-zero exit status 1

we wrapper up this script but I think you can get the idea. @memsharded
