### ISSUE TITLE
Package download fails inexplicably

### ISSUE THREAD

**Issue by youcefl** [conan-io/conan#349]
I have an issue I couldn't get around, the download of a package fails in the following way:
```
>conan  install -f "E:\***********************\x64\Release\cpp_pkg_ref.txt" -s "compiler=Visual Studio" -s "compiler.version=12" -s "build_type=Release" -s "arch=x86_64" -r conlan
llvm/3.7.1@y****/stable: Not found, retrieving from server 'conlan'
llvm/3.7.1@y****/stable: Trying with 'conlan'...
Downloading conanmanifest.txt
[==================================================]
Downloading conanfile.py
[==================================================]
Downloading conan_export.tgz
[================================================  ]                  ERROR: Download failed, check server, possibly try again
```
on the server side I have this:
```
[2016-06-29 17:42:30 +0000] [32295] [INFO] Booting worker with pid: 32295
[2016-06-29 17:42:30 +0000] [32287] [DEBUG] 4 workers
[2016-06-29 17:45:07 +0000] [32292] [DEBUG] GET /v1/conans/llvm/3.7.1/y****/stable/download_urls
[2016-06-29 17:45:12 +0000] [32292] [DEBUG] GET /v1/files/llvm/3.7.1/y****/stable/export/conanmanifest.txt
[2016-06-29 17:45:12 +0000] [32294] [DEBUG] GET /v1/files/llvm/3.7.1/y****/stable/export/conanfile.py
[2016-06-29 17:45:12 +0000] [32295] [DEBUG] GET /v1/files/llvm/3.7.1/y****/stable/export/conan_export.tgz
[2016-06-29 17:45:30 +0000] [32295] [DEBUG] Ignoring connection reset
```
The server runs on 64-bit Linux and the client is on Windows 10, the client conan version is 0.9.4.
Any help would be appreciated.

**Comment by lasote** [comment]
I will try to reproduce the error. What is the size of the package aprox?

**Comment by youcefl** [comment]
On the server side:
```
[y******@j******** conan_server2]$ ls -l ~/.conan_server/data/llvm/3.7.1/y********/stable/package/e0a02d496bbb652b6295152dfce0d3937acc0b56/
total 160396
-rw-r--r--. 1 y*** users       345 Jun 29 17:32 conaninfo.txt
-rw-r--r--. 1 y*** users     91272 Jun 29 17:32 conanmanifest.txt
-rw-r--r--. 1 y*** users 164146865 Jun 29 17:32 conan_package.tgz
```

**Comment by lasote** [comment]
That's 164 Mega bytes, correct?

**Comment by youcefl** [comment]
Yes, correct.

**Comment by lasote** [comment]
How long is taking the download until it fails? I'm trying to reproduce the error without success yet.

**Comment by youcefl** [comment]
It fails after about 25 seconds.

**Comment by youcefl** [comment]
I'm a bit confused and it seems I gave you the wrong number, the file the download of which fails
is not the 164MB above, I think it is this one:
```
[y____@j_____ conan_server2]$ ls -l ~/.conan_server/data/llvm/3.7.1/y____/stable/export/conan_exp*
-rw-r--r--. 1 yle users 1150301091 Jun 29 17:17 /home/y_____/.conan_server/data/llvm/3.7.1/y____/stable/export/conan_export.tgz
```
This one is ~1.07GB large

**Comment by lasote** [comment]
Wow, I can't even upload a package of 1GB to a conan_server. It raises Memory Error to me.
It will require handle package upload/download with streaming from disk, it's a little hard issue because it would need a big refactor. :(

**Comment by youcefl** [comment]
I also get memory error when uploading, but I worked around it by using 64-bit version installed with pip.
It is a kind of a blocker for me but I can stick to having the binaries in svn until a fix is available. Thank you for your help.

**Comment by youcefl** [comment]
You know what, while writing the previous comment I got the idea of using the 64-bit version for the download also and it worked!
```
C:\Python27>conan  install -f "E:\...\x64\Release\cpp_pkg_ref.txt" -s "compiler=Visual Studio" -s "compiler.version=12" -s "build_type=Release" -s "arch=x86_64" -r conlan
llvm/3.7.1@y__/stable: Not found, retrieving from server 'conlan'
llvm/3.7.1@y__/stable: Trying with 'conlan'...
Downloading conanmanifest.txt
[==================================================]
Downloading conanfile.py
[==================================================]
Downloading conan_export.tgz
[==================================================]
Requirements
    boost/1.55.0@y__/stable from conlan
    llvm/3.7.1@y__/stable from conlan
    protobuf/2.5.0@y__/stable from conlan
    pugixml/1.7.0@y__/stable from conlan
Packages
    boost/1.55.0@y__/stable:e0a02d496bbb652b6295152dfce0d3937acc0b56
    llvm/3.7.1@y__/stable:e0a02d496bbb652b6295152dfce0d3937acc0b56
    protobuf/2.5.0@y__/stable:e0a02d496bbb652b6295152dfce0d3937acc0b56
    pugixml/1.7.0@y__/stable:e0a02d496bbb652b6295152dfce0d3937acc0b56

boost/1.55.0@y__/stable: Already installed!
llvm/3.7.1@y__/stable: Installing package e0a02d496bbb652b6295152dfce0d3937acc0b56
llvm/3.7.1@y__/stable: Looking for package e0a02d496bbb652b6295152dfce0d3937acc0b56 in remote 'conlan'
Downloading conan_package.tgz
[==================================================]
Downloading conanmanifest.txt
[==================================================]
Downloading conaninfo.txt
[==================================================]
llvm/3.7.1@y__/stable: Package installed e0a02d496bbb652b6295152dfce0d3937acc0b56
protobuf/2.5.0@y__/stable: Already installed!
pugixml/1.7.0@y__/stable: Already installed!
PROJECT: Generated conaninfo.txt
PROJECT: Generated visual_studio created conanbuildinfo.props
PROJECT imports(): Copied 32 '.pdb' files
PROJECT imports(): Copied 33 '.dll' files
PROJECT imports(): Copied 6 '.exe' files
```

**Comment by lasote** [comment]
Great! I have referenced this issue from others too related. I think all this problems should be fixed with a streaming upload/download feature.

**Comment by memsharded** [comment]
This issue should be much improved with the upload with streaming from disk: https://github.com/conan-io/conan/pull/508

and download with streaming to disk: https://github.com/conan-io/conan/pull/497

They are already merged in develop, so will be released in next conan 0.13

**Comment by memsharded** [comment]
Released in conan 0.13.1

**Comment by Slonegg** [comment]
We still have this issue, almost all the time. It's either related to recent conan changes 0.19-0.21 or maybe something was changed in our proxy server configuration.

**Comment by memsharded** [comment]
Hi @Slonegg 

Could you please provide more details in order to try to investigate?
- Version of the client
- Version of the server
- Size of the package, time to download (beware of the gunicorn launch configuration of ``-t 120`` which is in seconds
- The traces of the failure, both in client and server.

Thanks very much!

**Comment by Slonegg** [comment]
Hi @memsharded. Seems that the problem was with gunicorn timeout. Thanks for suggestion.

**Comment by memsharded** [comment]
Great! happy it was solved.
