### ISSUE TITLE
OpenSSL is not supported on platform emscripten

### ISSUE THREAD

**Issue by JimmySnails** [conan-io/conan#5143]
To help us debug your issue please explain:

- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).
- [x] I've specified the Conan version, operating system version and any tool that can be relevant.
- [x] I've explained the steps to reproduce the error or the motivation/use case of the question/suggestion.

### Package and Environment Details (include every applicable attribute)
  * Package Name/Version: OpenSSL/1.1.1a
  * Operating System+version: Debian Stretch
  * Compiler+version: emscripten toolchain compiler
  * Docker image: none ?
  * Conan version: Conan 1.15.0
  * Python version: Python 3.5.3

### Conan profile (output of `conan profile show default` or `conan profile show <profile>` if custom profile is in use)
```
[settings]
os=Emscripten
arch=asm.js
os_build=Linux
arch_build=x86_64
compiler=clang
compiler.version=6.0
compiler.libcxx=libc++
[options]
[build_requires]
emsdk_installer/1.38.22@bincrafters/stable
[options]
libjpeg-turbo:SIMD = False
```

### Steps to reproduce (Include if Applicable)
build OpenSSL/1.1.1a for emscripten

### Logs (Include/Attach if Applicable)

```
OpenSSL/1.1.1a@conan/stable: ERROR: Package '4d26d78a37374f38419f1607939e7de75f52abf5' build failed
OpenSSL/1.1.1a@conan/stable: WARN: Build folder /home/cwelsch/.conan/data/OpenSSL/1.1.1a/conan/stable/build/4d26d78a37374f38419f1607939e7de75f52abf5
ERROR: OpenSSL/1.1.1a@conan/stable: Error in build() method, line 89
	raise Exception("Unsupported operating system: %s" % self.settings.os)
	Exception: Unsupported operating system: Emscripten
```

**Comment by Johnnyxy** [comment]
hi there,
I checked my local ```settings.yml``` ([see docs](https://docs.conan.io/en/latest/reference/config_files/settings.yml.html#settings-yml)) from my Conan 1.15.0 installation. It conatins an entry for os "Emscripten".

Probably you are facing a similar issue like this one: https://github.com/conan-io/conan/issues/5128

**Comment by JimmySnails** [comment]
I guess you mean this entry:

```
   Emscripten:
arch: [x86, x86_64, ppc32, ppc64le, ppc64, armv4, armv4i, armv5el, armv5hf, armv6, armv7, armv7hf, armv7s, armv7k, armv8, armv8_32, armv8.3, sparc, sparcv9, mips, mips64, avr, s390, s390x, asm.js, wasm]
```

I don't have a settings.yml.new

Also, a lot of the other dependencies can be built (or fail in another way...) 
Is there another place where i should look?

**Comment by Johnnyxy** [comment]
Then from Conan side it should be working.

The error you mentioned originates in the ```def build(self)``` function of the recipe:
> ERROR: OpenSSL/1.1.1a@conan/stable: Error in build() method, line 89

Where did you get the recipe?
Can you provide the recipe as attachment or if possible a link to it?

**Comment by JimmySnails** [comment]
I'm sorry, i'm quite a conan noob...

It's just a line in my conanfile.txt
```
[generators]
cmake

[requires]
sdl2/2.0.9@bincrafters/stable
sdl2_ttf/2.0.15@bincrafters/stable
sdl2_image/2.0.4@bincrafters/stable
sdl2_mixer/2.0.4@anotherfoxguy/stable
libpng/1.6.36@bincrafters/stable
freetype/2.9.1@bincrafters/stable
libnoise/1.0.0@anotherfoxguy/stable
OpenSSL/1.1.1@conan/stable
qt/5.12.3@bincrafters/stable

[options]
sdl2_mixer:opus=False # PACKAGE:OPTION=VALUE
```

What do you mean by where i got the recipe from? Is this the conanfile.py? It downloaded itself automatically.

**Comment by Johnnyxy** [comment]
The problem is in the OpenSSL recipe.
For version 1.1.1a the executed code is this:
```python
    def build(self):
        if self.settings.os in ["Linux", "SunOS", "FreeBSD", "Android", "Macos"] or \
                (self.settings.os == "Windows" and self.compiler == "gcc"):
            self.unix_build()
        elif self.settings.os == "iOS":
            self.ios_build()
        elif self.compiler == "Visual Studio":
            self.visual_build()
        else:
            raise Exception("Unsupported operating system: %s" % self.settings.os)
```
Version 1.1.1a does not support Emscripten at the moment.

This is maintained by the conan-center-community ([link](https://bintray.com/conan-community/conan/OpenSSL%3Aconan)).
So you have to head over there and inform them about your issue ([link](https://github.com/conan-community/community/issues)).

**Comment by JimmySnails** [comment]
Thank you, i've created an issue over there:
https://github.com/conan-community/community/issues/206

Going to close this.

**Comment by Axil-ww** [comment]
Excuse me, but I still don’t understand anything. Can I build OpenSSL for Emscripten or not? If yes, how to do it under Windows? What is conan?
Help, I am a simple Visual C ++ programmer and do not understand anything about this.

**Comment by uilianries** [comment]
> This is maintained by the conan-center-community (link).

No, the link is wrong. Conan Center Index and Conan Community are different communities.

The OpenSSL version provided by Conan Community is deprecated. Use the version provided by Conan Center Index instead.

https://github.com/conan-io/conan-center-index/tree/master/recipes/openssl/ALL

    conan search -r conan-center "openssl/1.1.1d@"

**Comment by Axil-ww** [comment]
I ran this search but could not find the package under Emscripten.

**Comment by memsharded** [comment]
> I ran this search but could not find the package under Emscripten.

ConanCenter does not provide pre-compiled binaries for Emscripten, only for main Windows, Linux and OSX compilers and configurations (around 130 different binaries for each package version).

The Conan recipes might be used to build from sources different packages, and providing the right inputs you can try to build them for emscripten. That doesn't mean that all recipes in ConanCenter will correctly build for emscripten.

**Comment by Axil-ww** [comment]
How to use recipes? I did not find this in the documentation.
"ImportError: No module named conans.errors"

**Comment by Axil-ww** [comment]
How to use conan to build from recipe?
I ran this command:
`conan install path_to\conan-center-index-master\recipes\openssl\ALL\conanfile.py`
Everything needed was downloaded to "c:\.conan\" and "c:\Users\username\.conan\data\": emsdk, strawberryperl, clang, python, etc.
And nothing happened.

**Comment by Axil-ww** [comment]
I understood how it works a little. Download conan-openssl-master.zip , replace recipe from conan-center-index-master.zip
`conan install ..`
`conan create .. conan/stable`
Wrote the version="1.1.1d" directly in conanfile.py
But it is not work, same error:
`openssl/1.1.1d@conan/stable: ERROR: Package '0f84630460d163bb1f9eb4fdc7a6a53059b7ff62' build failed
openssl/1.1.1d@conan/stable: WARN: Build folder C:\Users\username\.conan\data\openssl\1.1.1d\conan\stable\build\0f84630460d163bb1f9eb4fdc7a6a53059b7ff62
ERROR: openssl/1.1.1d@conan/stable: Error in build() method, line 593
        self._make()
while calling '_make', line 561
        self._run_make()
while calling '_run_make', line 521
        self.run(" ".join(command), win_bash=self._win_bash)
        ConanException: Error 2 while executing /c/.conan/6eae6c/1/bin/usr/bin/make.exe -j8
`

**Comment by Axil-ww** [comment]
`openssl/1.1.1d@conan/stable: /usr/bin/python: can't open file '/:\.conan\80304d\1\emscripten\1.38.22\emcc.py': [Errno 2] No such file or directory`

Why /:\.conan but not c:\.conan ?

**Comment by Johnnyxy** [comment]
The error message states that it is trying to access a path in a Unix-style environment ```/home/user/folder/...``` but it was given a Windows style path ```c:\Users\user\folder\...``` (see [here](https://en.wikipedia.org/wiki/Path_%28computing%29#Representations_of_paths_by_operating_system_and_shell)).

I did not look into the recipe but it looks like you are executing some Unix like environment on Windows (e.g. Cygwin). This in turn means that the paths have to be converted from Windows-style to Unix-style.
