### ISSUE TITLE
[workspaces] Bug when using workspaces with remote update

### ISSUE THREAD

**Issue by climblinne** [conan-io/conan#5228]
To help us debug your issue please explain:

- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).
- [x] I've specified the Conan version, operating system version and any tool that can be relevant.
- [x] I've explained the steps to reproduce the error or the motivation/use case of the question/suggestion.

I am using Conan 1.5.1 on a Windows 10 operating system in combination with an Artifactory server.
I use semver `[~0.1.0]` to determine dependencies from libraries. On the remote there is a version `0.1.0` available. Now I try to use my own local library instead of the remote / cached one.
When using `conan workspace install ..\conanws_vs.yml -u` my library is cached instead of editable. On the other side, applying the following without update  `conan workspace install ..\conanws_vs.yml ` everything works fine.
There must be a bug in combination with semver and remote update in the conan workspace command. 

_Here the recipe to reproduce the error:_ 

Starting with the existing example:
```
$ git clone https://github.com/conan-io/examples.git
$ cd features/workspace/cmake
```

And add the following diff
```diff
 features/workspace/cmake/chat/conanfile.py  | 2 +-
 features/workspace/cmake/conanws_vs.yml     | 2 +-
 features/workspace/cmake/hello/conanfile.py | 2 +-
 3 files changed, 3 insertions(+), 3 deletions(-)

diff --git a/features/workspace/cmake/chat/conanfile.py b/features/workspace/cmake/chat/conanfile.py
index 7f77070..364f6db 100644
--- a/features/workspace/cmake/chat/conanfile.py
+++ b/features/workspace/cmake/chat/conanfile.py
@@ -6,7 +6,7 @@ class Pkg(ConanFile):
     settings = "os", "compiler", "arch", "build_type"
     generators = "cmake"
     exports_sources = "src/*"
-    requires = "hello/0.1@user/testing"
+    requires = "hello/[~0.1.0]@user/testing"
 
     def build(self):
         cmake = CMake(self)
diff --git a/features/workspace/cmake/conanws_vs.yml b/features/workspace/cmake/conanws_vs.yml
index 4ddff31..3d094ca 100644
--- a/features/workspace/cmake/conanws_vs.yml
+++ b/features/workspace/cmake/conanws_vs.yml
@@ -1,7 +1,7 @@
 editables:
     say/0.1@user/testing:
         path: say
-    hello/0.1@user/testing:
+    hello/0.1.1@user/testing:
         path: hello
     chat/0.1@user/testing:
         path: chat
diff --git a/features/workspace/cmake/hello/conanfile.py b/features/workspace/cmake/hello/conanfile.py
index 34684c2..374c137 100644
--- a/features/workspace/cmake/hello/conanfile.py
+++ b/features/workspace/cmake/hello/conanfile.py
@@ -2,7 +2,7 @@ from conans import ConanFile, CMake
 
 class Pkg(ConanFile):
     name = "hello"
-    version = "0.1"
+    version = "0.1.0"
     settings = "os", "compiler", "arch", "build_type"
     generators = "cmake"
     exports_sources = "src/*"
```

Create the "hello" package and upload it to the remote server:
```
> conan search hello -r conan-ivc
Existing package recipes:
hello/0.1.0@user/testing
``` 

Now run the following command from the build folder:
```
build> conan workspace install ..\conanws_vs.yml -u
```
It returns:
```
hello/0.1.0@user/testing: WARN: Can't update, no package in remote
Version ranges solved
    Version range '~0.1.0' required by 'chat/0.1@user/testing' resolved to 'hello/0.1.0@user/testing'

Requirements
    hello/0.1.0@user/testing from 'conan' - Cache
    chat/0.1@user/testing from user folder - Editable
    say/0.1@user/testing from user folder - Editable
Packages
    hello/0.1.0@user/testing:98ce62312cb8b844c4a47cba2e495294a7e3e4ba - Cache
    chat/0.1@user/testing:011d66d9e03f7570d37d2a2189069a9c8e73562c - Editable
    say/0.1@user/testing:6cc50b139b9c3d27b3e9042d5f5372d327b3a9f7 - Editable
```

When using without update everything works fine:
```
build> conan workspace install ..\conanws_vs.yml 
```
```
Version ranges solved
    Version range '~0.1.0' required by 'chat/0.1@user/testing' resolved to 'hello/0.1.1@user/testing'

Requirements
    chat/0.1@user/testing from user folder - Editable
    hello/0.1.1@user/testing from user folder - Editable
    say/0.1@user/testing from user folder - Editable
Packages
    chat/0.1@user/testing:1443e56dba34d010cc5d9487455f673fa878e60f - Editable
    hello/0.1.1@user/testing:98ce62312cb8b844c4a47cba2e495294a7e3e4ba - Editable
    say/0.1@user/testing:6cc50b139b9c3d27b3e9042d5f5372d327b3a9f7 - Editable
```

**Comment by jgsogo** [comment]
Hi, @climblinne!

This is an issue we have already seen related to the workspace feature. Yes, during graph resolution the version ranges are resolved taking into account the existing packages in the cache (or even the remote). We need to use some kind of lock to force Conan to use the references included in the workspace to resolve some version ranges.

Right now this is an open issue that we want to fix asap, we think we need the _lockfiles feature_ before (https://github.com/conan-io/conan/pull/5035) in order to solve this one on top of that functionality.

**Comment by climblinne** [comment]
Hopefully you will get this done to the next milestone 1.6. Can I support somehow?

**Comment by jgsogo** [comment]
Not for `v1.16` 😞 , although we have our best man working on the graphlock feature, then we have to gather all the feedback we already have about workspaces and make a new iteration. I'm pretty sure we are going to work on this during June, so maybe for `v1.17` we can release an improved version of workspaces.

**Comment by climblinne** [comment]
I just tested 1.17.2 with it, still not working. Will it be in the next release cycles?

**Comment by climblinne** [comment]
@jgsogo Is there any chance to fix this issue? I tested today in version 1.19.2 and still the same issue.

**Comment by klimkin** [comment]
Is the issue addressed in the current version?

**Comment by memsharded** [comment]
Workspaces were removed in 2.0, but the plan is to resume work on them in the 2.X roadmap.
Please track progress in https://github.com/conan-io/conan/issues/12466, closing this
