### ISSUE TITLE
Injection of SVN credentials during installation phase when using SCM capturing

### ISSUE THREAD

**Issue by jasal82** [conan-io/conan#5595]
I'm using SCM url and revision capturing to be able to keep the conanfile.py in my SVN source repository. What I have is an attribute

```
    scm = {
        "type": "svn",
        "url": "auto",
        "revision": "auto",
        "subfolder": bundleName,
        "username": tools.get_env("SVNUSER"),
        "password": tools.get_env("SVNPASS"),
    }
```

Username and password for the SVN repo is injected via environment variables so that CI jobs can use a generic build user. This works fine for building the package and exporting it. However, if I have a downstream package depending on the one above Conan fails to download the sources during the installation phase because the password setting was deleted from the recipe upon export.

How can I inject SVN credentials to be used during the installation phase? I think it would be necessary to actually implement the `source()` method in the upstream package (which is - as far as I understood - defined implicitly when using the `scm` property), create an instance of tools.SVN providing username/password in the constructor, and then use the captured scm metadata for url and revision.

**Comment by jasal82** [comment]
It just occured to me that the `username` and `password` settings are actually not necessary for creating the package. A working copy of the repository is already checked out due to the fact that the conanfile is located in the source repository. If they are not stored in the recipe for later use during consumption I could just as well remove them from the `scm` attribute.

However, the question about how to inject SVN credentials to be used during package consumption is still valid.

**Comment by jgsogo** [comment]
Hi, @jasal82. Let me explain to you how the `scm` attribute works and then we can try to imagine the best way to achieve what you want to do.

When Conan creates a package, during the _export_ stage, the `scm` attribute in the `conanfile.py` is evaluated, the values are computed (python code is executed, so the `auto` keywords are resolved, any function is called, and any environment variable is evaluated) and the exported recipe in the cache contains the exported values (you can run `conan get <ref>` to check it).
 * In your use case, if the environment variables are missing, your `scm` members `username` and `password` will be evaluated to `None` and the exported recipe will only contain `scm` member with values other than `None`.

⚠️ If you use a password here, the password will be written in the recipe and uploaded to the server, any user that access to the recipe will be able to read the password. So **I would strongly recommend using a user with read-only permissions** if you use this approach, and hardcode the `username` and `password` fields.

**Comment by jasal82** [comment]
Thanks for the explanation. My first try was actually *with* the `username` and `password` fields set, however, it seems that the password is removed in the recipe which is uploaded to the server. I remember an entry in the recent Conan changelogs that mentioned the introduction of that said removal feature, so that approach does not work for me.

**Comment by jgsogo** [comment]
That PR eliminates the password from the URL, but if it is explicit in the `scm::password` field it will be stored and exported in the recipe source. Right now, having different passwords per URL and Conan choosing the appropiate one, together with the `auto` functionality, may work but with some constraints, something like:

```python
def get_password(url):
    if url.startswith(".... A"):
        return tools.get_env("SVNPASS_URL_A")
    elif url.startswith(".... B"):
        return tools.get_env("SVNPASS_URL_B")
    else ...


class Recipe(ConanFile):
    scm = {...
           "url": "..... A",
           "revision": "auto",
           "password": get_password(".... A")
           }
```

We already have a `proxies` section in the Conan configuration, there you can redirect or embed user/password for domains you choose. Reading the YOCTO link you have provided I see that it is not just about a proxy, it is a fallback strategy to look for the sources at different proxies (maybe per URL, not just per domain). I know I'm simplifying, this is something to look into and think about.

**Comment by jasal82** [comment]
I just noticed that the password is indeed exported correctly. The order of the attributes is different in the exported recipe so I expected it next to the username. Unfortunately I still can't make it checkout the sources. Conan just says `Not a valid 'svn' repository`. Is there a way to enable logging of the actual svn client error messages?

**Comment by jasal82** [comment]
After inspection of the `conan create` command on the consuming package with strace I found that - even though username and password are correctly set in the dependency's recipe in the local cache - Conan does not forward it to the `svn co` call. What I get is only

```
execve("/usr/bin/svn", ["svn", "co", "https://repo/url@211650", ".", "--no-auth-cache", "--non-interactive", "--trust-server-cert-failures=unknown-ca"], ...)
```

This is on Conan 1.18.1. What am I missing?

**Comment by jasal82** [comment]
It's simply not implemented. Git uses the url retrieved from `get_url_with_credentials()`. SVN uses the base url without any credentials and also does not forward them to the client via `--username` and `--password`. This is a bug.

**Comment by jgsogo** [comment]
Thanks a lot for the investigation 👍

**Comment by jgsogo** [comment]
Hi, @jasal82 I think that we can close this issue given the bug and PR you submitted, now that it is merged (it will be shipped with Conan `v1.19` by the end of the month). If there is anything else you want to comment, just tell me.

Thanks for your contribution.

**Comment by jasal82** [comment]
Thanks for your help. The fix will do for me so I'll close this issue.
