### ISSUE TITLE
[bug] Conan with Artifactory fails to download large packages

### ISSUE THREAD

**Issue by ghost** [conan-io/conan#7498]
Hello All,

Potentially related to issues: #1901 #3580 #6995

We recently migrated our Conan Server from the Conan provided server to Artifactory's Server and we are having issues downloading very large packages (~2.6Gigs).  Since we did not have this issue before, it is safe to assume that this issue comes from the change in Server (Server's fault, or Conan/Server not interfacing properly).   

When performing a conan install about 1Gig (38%) of the file gets installed, it then instantly completes the installation and errors out with the following error (repeating):
```
Downloading conanmanifest.txt completed [10.94k]                                         
Downloading conaninfo.txt completed [0.15k]                                              
Downloading conan_package.tgz completed [1067783.34k]                                    
ERROR: Download failed, check server, possibly try again
Download failed, check server, possibly try again
Error in resumed download from <server_url>
Incorrect Content-Range header 
Waiting 0 seconds to retry...
Downloading conan_package.tgz completed [1067815.34k]                                    
ERROR: Download failed, check server, possibly try again
Download failed, check server, possibly try again
Error in resumed download from <server_url>
Incorrect Content-Range header 
Waiting 0 seconds to retry...
```

### Environment Details (include every applicable attribute)
  * Operating System+version: RHEL7/Ubuntu Bionic
  * Conan version: 1.28.0
  * Python version: python3.6.8
  * Artifactory Server Type: Community
  * Artifactory Server Version: 7.5.7
  * Proxy: Network is proxied but we shouldn't be using it b/c we are all on the same subnet
  * Issue occurs with SSL: True and SSL: False

### Steps to reproduce
conan install <package greater than 2.5 gigs on a slow network: (0.800ms ping / 90Mbits/sec throughput)>

### logs:
[conan_trace.txt](https://github.com/conan-io/conan/files/5024994/conan_trace.txt)

**Comment by memsharded** [comment]
Quick check, I guess you mean ``conan 1.28.0``, as ``1.28.1`` has not been released yet.

Also quick question: in which system are you running the Artifactory CE? In the same one? The docker one?

**Comment by ghost** [comment]
yes 1.28.0, sorry.  We have 1 instance of Artifactory Community Edition which has the conan add on.  No docker, and nothing fancy going on besides configurable SSL (if that counts).

```
{
  "version" : "7.5.7",
  "revision" : "70507900",
  "addons" : [ "conan" ],
  "license" : "Artifactory Community Edition for C/C++"
}
```

**Comment by memsharded** [comment]
> yes 1.28.0, sorry. We have 1 instance of Artifactory Community Edition which has the conan add on. No docker, and nothing fancy going on besides configurable SSL (if that counts).

Yes, that might be a potential cause. We have found sometimes the limit was an Nginx frontend, not Artifactory, for example. Could you please try to run with the bare server (no SSL, just out of the box) if possible, to try to rule out that possible cause?

**Comment by ghost** [comment]
The same issue happens when I use the Server's HTTP remote,  HTTPS with SSL=False, and HTTPS with SSL=True.

When I run with an older version of conan (1.16.1), I get a different (potentially useful) error:
```
ERROR: Download failed, check server, possibly try again
Transfer interrupted before complete: 1092418911 < 2799985649   // These numbers are the same on every iteration
```

**Comment by ghost** [comment]
I just got it to pass (multiple times) on multiple different boxes on our network.  The error seems to be isolated to a few different client boxes. The specific boxes that are having issues are only having issues with big packages (they get small packages just fine, including small packages over VPN). My $CONAN_USER_HOME is located on a NFS shared between problem and non-problem boxes, so my setting are exactly the same.  This seems like a networking issue on my end.  Do you have any tips to help me debug this? 

I got it working with several different versions of conan with/without SSL on the non-problem boxes.

PS: Its called Artifactory b/c it is an art to get it working right lol

**Comment by memsharded** [comment]
Hi @szegel 

Yeah, networks can be problematic, this is why we first added retries on the failed downloads, and recently we merged support for resumable downloads for large packages, which has improved the situation. What you are seeing in previous Conan versions like ``Transfer interrupted before complete: 1092418911 < 2799985649`` is an interrupted download that was not resumed, this is why the output is different.

I am not sure what could be checked next, obviously to find some software or hardware difference between the working and failing boxes:

- All of them use exactly the same RHEL7/Ubuntu Bionic OS? Are the failing ones one OS and the working ones other one? Any consistent difference there?
- Any special characteristic of the network, the topology that could be different?
- The NFS system, has a different folder for each box? The Conan cache is not designed for concurrency, so even if it can be in a network share, it shouldn't be shared among clients
- Was the builtin conan_server serving those huge binaries reliably to those failing boxes too? Our experience is mostly the opposite, we recommend Artifactory because it is faster, more feature complete and scales and handles load much better.

The fact that the download is interrupted at exactly the same byte at every attempt is very relevant. Seems that some memory limit, filter or check is being triggered at some layer in the software or hardware infrastructure, but yeah, this might be an interesting bug hunt. Some things that I would try:

- Check and compare resource limits, memory, disk of the failing boxes. Check and compare the python installed there, does it match the architecture 32/64bits? Everything identical?
- Put a local Artifactory CE in one of the failing machines. See if it works or still fail. 
- If locally works, I would try in some kind of local network, like in another computer attached to the same router.
- Investigate the office or data center network infrastructure and setup.

**Comment by ghost** [comment]
Thanks for the help James, I really appreciate it! I am still investigating and haven't gotten around to everything you said, but here is an interesting update:

I think it may have something to do with network speed (note: I set CONAN_USER_TIMEOUT=5000 with no change in effect, not a conan timeout impacted by that variable). The "good" and "bad" boxes are on the same subnet (network config), same hardware, and same OS.  See latency/throughput measurements:

### Latency/Throughput:
Artifactory Server -> Good Box: 0.264 ms / 699 Mbits/sec
Artifactory Server -> Bad Box: 0.853 ms/ 96.3 Mbits/sec  // 100Mbits/sec is still not "slow"
Artifactory Server -> VPN: 100.5 ms / 7 Mbits/sec  // this is very slow

I would still expect Conan to work even on a slow network.  It is interesting that bandwidth (90Mbits/sec) + package size (2.5Gigs) is causing some issues.  My suspects are still on the server b/c this behavior just started when we switched to Artifactory (conan worked for big packages on "good", "bad" and vpn boxes). Conan with small packages still works correctly on all 3 cases.

**Comment by markgalpin** [comment]
Not sure if this will fix it, but one thing that jumps out at me: If your package size is that large, you may want to increase the size of the JVM.  The default JVM maxes out at 2 GB, if you have enough memory on your machine you may want to up it to 4 GB (or half of the available RAM depending on how you're  hosting it).   In the system.yaml configuration file you should see a line:
```
shared:
   extraJavaOpts: "-Xms512m -Xmx2g"
```
adjust it to:
```
   extraJavaOpts: "-Xms1g -Xmx4g"
```
While Artifactory can handle being memory cramped, its often a little less robust in those instances.   In general Artifactory is pretty robust to slow networks, it can be somewhat less robust to dropped packets (though hopefully conan retries handles this issue better).  TBQH this shouldn't be the major cause of the problem, but it will probably help performance overall.  I would also love to know what you're seeing in the artifactory-service.log and the artifactory-request.log for these requests.  Does anything show up on that side?

**Comment by ghost** [comment]
I also was mistaken about the transfer interrupt memory block always being the same (sorry for confusion).  I think I did see the same number a couple times (or maybe I was tired).
Transfer interrupted before complete: 1092369759 < 2799985649
Transfer interrupted before complete: 1091468639 < 2799985649
Transfer interrupted before complete: 1093139807 < 2799985649

**Comment by ghost** [comment]
Hey @markgalpin,

I have attached the logs you have requested.  The settings of my server were at  `extraJavaOpts: "-Xms512m -Xmx8g"` already, so I changed them to `extraJavaOpts: "-Xms1g -Xmx8g"` (viewable in the server log).  I forgot to mention we also have LDAP configured, but that is working fine and I think it is unrelated to this issue.  Unfortunately, it didn't fix anything.

### Logs
[artifactory-request-segment.log](https://github.com/conan-io/conan/files/5030741/artifactory-request-segment.log)
[artifactory-service.log](https://github.com/conan-io/conan/files/5030703/artifactory-service.log)

**Comment by markgalpin** [comment]
So what is quite strange is that artifactory is recording that it successfully sent you the entire object.  You're sure you're not going through some sort of cacheing or proxy layer imbetween?  This feels like a proxy choking on something, rather than an issue with the artifactory server itself.  So, from a 'bad' machine, what's the output of:
`curl -I -u<admin>:<password> -vvv -L 'http:<artifactory baseURL>/artifactory/api/conan/conan-local/v1/files/user/package/version/release/0/package/5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9/0/conan_package.tgz'`

**Comment by ghost** [comment]
Sorry for the delay!  The issue shows up on CURL so that fully exonerates the Conan client API, and pushes the issue to our Network and/or to the Artifactory server.  (And yes our package has grown to 4.5 G)

Good Box:
```
100 4491M  100 4491M    0     0  12.6M      0  0:05:55  0:05:55 --:--:-- 48.1M
```

Bad Box:
```
 23 4491M   23 1038M    0     0  10.2M      0  0:07:17  0:01:41  0:05:36  9.8M* transfer closed with 3617697932 bytes remaining to read
 23 4491M   23 1041M    0     0  10.2M      0  0:07:17  0:01:41  0:05:36 9729k
* Closing connection 0
curl: (18) transfer closed with 3617697932 bytes remaining to read
```

**Comment by czoido** [comment]
Hi @szegel,
Are you still having this issue? I have created a script trying to reproduce here: https://github.com/czoido/issue-7498 but I was not able to reproduce the issue to date. Did you find out anything more about this?
Please, if anyone can try to reproduce it would be of great help.
Thanks!

**Comment by mvtec-richter** [comment]
Hello!

We had a very similar issue with conan and our artifactory instance. The download also stopped at almost exactly 1G, but only on slow connections. We also got an "Incorrect Content-Range header" error message from conan.

Additionally to slow VPN connections, we could reproduce this on machines with a fast connection to the artifactory server when rate limiting the download:
curl -u<username> -L https://.../conan_package.tgz -o test.tgz --limit-rate 5m

We could track down this to the nginx proxy:
I found this post on stackoverflow:
https://stackoverflow.com/questions/63586635/artifactory-downloads-terminate-prematurely-due-to-nginx-reverse-proxy-configura

They suggest to disable proxy_buffering, which fixed the issue for us. 

proxy_buffering off;
proxy_ignore_headers "X-Accel-Buffering";

I hope, this is helpful to someone.

**Comment by hpesoj** [comment]
This seems to have nothing to do with proxies. Simply rate-limiting the download causes Artifactory to abort the download. Try this:
```
curl https://center.conan.io/artifactory/api/conan/conan-center/v1/files/_/android-ndk/r22/_/ffc0e4ddaf1079113c866578962420af/package/4db1be536558d833e52e862fd84d64d75c2b3656/ee43eea6617c0a5f69a7a65ca07622ff/conan_package.tgz --limit-rate 3M --output conan_package.tgz
```
Results in (at ~1035MB):
```
curl: (18) transfer closed with 54337182 bytes remaining to read
```
Unfortunately, this means we can't download large files when the connection is slow.

**Comment by memsharded** [comment]
This seems an outdated issue, originally posted 4 years ago:

- We have had no other reports about this behavior, seems something specific to the network/setup of the OP
- @mvtec-richter had a similar issue, and it was also due to the ``proxy_buffering, which fixed the issue for us`` configuration.
- Regarding the comment by @hpesoj about `` https://center.conan.io/`` that is a different one, tracked in #9412 (still WIP), but due to Google cloud limits apparently.

So far, it doesn't seem something that we can do on our end, and not an issue in Conan client or in Artifactory, so I am closing it. Please don't hesitate to open new tickets if necessary. Thanks!

**Comment by bldrvnlw** [comment]
Were are still encountering this with artifactory-cpp-ce:7.59.11. 

It's not a conan specific issue and is reproducable ith an artifact > 1GB and a rate limited download. As noted above this can be simulated in curl with --limit-rate . In our case we are seeing the issue around --limit-rate at 15m. 

If the client (either conan or curl) is on a fast connection to the artifactory you won't see the issue.

My feeling is that it has to do with the mismatch between the speed at which the artifactory backend can provide the file to the nginx proxy and the rate at wich the proxy forwards this to the client.  We have the setting proxy_buffering off; but I'll also try the proxy_ignore_headers "X-Accel-Buffering"; as suggested.

**Comment by bldrvnlw** [comment]
Unfortunately in our case the nginx settings (as suggested) don't help.: 

proxy_buffering off;
proxy_ignore_headers "X-Accel-Buffering";

**Comment by franramirez688** [comment]
> So far, it doesn't seem something that we can do on our end, and not an issue in Conan client or in Artifactory, so I am closing it. Please don't hesitate to open new tickets if necessary. Thanks!

Closing this again, as I can reconfirm it's not the same as https://github.com/conan-io/conan/issues/9412. This issue is talking about the Nginx as a reverse proxy (more info [here](https://jfrog.com/help/r/jfrog-artifactory-documentation/configure-nginx)) itself instead of the Conan Center Index.

> Unfortunately in our case the nginx settings (as suggested) don't help.:
proxy_buffering off;
proxy_ignore_headers "X-Accel-Buffering";

@bldrvnlw thanks a lot for your recent feedback. I've been involved in resolving the mentioned issue, and I can give you some tips that I've found while looking into this:

* Using `proxy_buffering off;` depends on a robust backend, so it could be a bit "risky" when it's not completely our case. For instance:

```
    proxy_buffering      off;
    proxy_ignore_headers "X-Accel-Buffering";  # ensures buffering off
    proxy_read_timeout   1800s; # Still needed for backend pauses
    send_timeout         1800s; # Still needed for client pauses
```
* If it does not work, I'd try the buffers + bigger temp file (if your hardware can fit these requirements):

```
      proxy_buffer_size           256k;
      proxy_buffers               4 256k;
      proxy_busy_buffers_size     256k;
      proxy_max_temp_file_size    2048m;   # up to 2 Gb or the biggest size that could be found in your artifacts
```
Obviously, these are some little recommendations that could help to solve the issue, but I do not have a canonical answer to solve this because of the dependence on each single infrastructure capability.

**Comment by bldrvnlw** [comment]
@franramirez688 Thanks for looking into this again. Indeed it is not about the Conan Center Index but we are using the jfrog cpp-ce docker setup on out own server with nginx as proxy.   

I'll double check the options. For the moment we are advising the user with the slow connection to install manually (via another fast machine) so we do have a workaround.
