### ISSUE TITLE
[question] Packaging and deploying unittests

### ISSUE THREAD

**Issue by zawlin** [conan-io/conan#9977]
What is the recommended workflow for running unit tests in a stripped down environment where conan might not be available? 

To further explain our situation, we are trying to make conan work in CI pipeline where we have a 1) build stage 2) run unit tests 3) build package tests 4) run package tests. We are required not to run unit tests on the same build image and use an extremely minimal docker image to run unittests.  One of the reason for this after we built it one platform say ubuntu18, it needed to be tested in multiple platforms such as ubuntu20,18, and ubi8. We solve this for package testing by creating a new conan package and defining deploy() method so that the resulting test binary can be run independently and the test package recipe itself is treated as throwaway and not pushed to artifactory.

However, for unittesting, since they might use internal classes, they needed to be built together in build stage. So the issue now is what is the way to exclude unit tests binaries in the final package that gets pushed to artifactory?

- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

**Comment by memsharded** [comment]
Hi @zawlin 

I'd need to understand better the level of visibility needed of your unittests, because you are telling at the same time that ``However, for unittesting, since they might use internal classes, they needed to be built together in build stage. `` and that you need to run them separately in a different image which is not the build image (so I assume that you need to copy the built binary artifacts and the public headers to the test image). Both seems to be contradictory, could you please clarify the issue? Thanks.

**Comment by zawlin** [comment]
The public headers do not need to be copied to the test image. Let's say for LIB A

* If we have this flag `-DBUILD_TESTING:BOOL=ON`, it will generate test binaries in install/test folder.
* `conan create . _/_` to create the package which will also package test folder and make the library available in local cache.
* `conan install LIBA/0.0.1@  -pr=ubuntu18 -if tests` we define deploy() method to copy only tests to tests folder 
* `tests` folder and the entire conan cache is transferred to next stage in pipeline. Let's assume that build image and test image will share the same folder structure so that rpath issues can be ignored.
* binaries under `tests` are executed in test image

Now we know that test is ok and we don't need those binaries anymore in final package. How can we avoid it?

**Comment by memsharded** [comment]
It is not possible to eliminate files/artifacts from a package that has been created. Packages are immutable, they cannot be modified, as their artifacts define their identity (revisions, both recipe and package revisions). The possibility would be:

- Add a ``bundle_tests`` option, so you have 2 different binary packages, one that bundles the tests and one that doesnt (production).
- You will also typically activate ``-DBUILD_TESTING:BOOL=ON`` conditioned to that option.
- You can leverage the ``build_id()`` method to avoid building twice, by removing this option from the ``build_id`` identifier. Then call 2 different ``conan create`` changing the option, it will be built once, and package twice.

Instead of doing ``deploy``, you can also use a ``virtualenv`` approach, that defines the paths to the executables, and that can avoid moving around the binaries. Something like the ``-g VirtualRunEnv`` new environment. Still the ``rpaths`` issue will always be there if the caches locations are different. If VirtualRunEnv definition of LD_LIBRARY_PATH is good enough, then this could be a good approach.

**Comment by zawlin** [comment]
Thank you. I think this will work. I will have to try it out.

**Comment by SpectreVert** [comment]
@zawlin Hello, I'm looking to deploying a very similar setup.

Do you have any feedback about the approach suggested by memsharded if you did go through with it?

Kind regards

**Comment by memsharded** [comment]
Hi all,

There are good news here. We have implemented a new feature, the "metadata files" feature, that allows to store and manage all kind of metadata, from logs to tests, to results of unittests, etc.
It is already merged and released in Conan 2.0, but it has not been documented yet, not launched. We are finishing some details and it will be launched soon.

If you are curious and want to have a quick look and try things, the tests can help and illustrate the usage: https://github.com/conan-io/conan/tree/release/2.0/conans/test/integration/metadata. For example https://github.com/conan-io/conan/blob/release/2.0/conans/test/integration/metadata/test_metadata_test_package.py shows how to store the full ``test_package`` in the metadata and recover it from there to execute.

**Comment by SpectreVert** [comment]
Hi memsharded,

Thanks for the heads up! That feature might very well be enough for what I'm trying to do. I will go try it out and report back here.

**Comment by SpectreVert** [comment]
So I've been manually trying the commands in https://github.com/conan-io/conan/blob/release/2.0/conans/test/integration/metadata/test_metadata_commands.py but I am stuck around line 54 on the `Forcing the download of the metadata of cache-existing things with the "download" command` step. I get this error:

```
(venv) spectrevert@machine ~
> conan download pkg/1.0 -r myremote --metadata='*'
ERROR: 500: org.jfrog.repomd.conan.exceptions.ConanInfoException: Missing section in conaninfo.txt. [Remote: myremote]
```

I have only uploaded recipe metadata: `pkg/1.0: Recipe metadata: 1 files` if that might change anything.

I am using `conan 2.0.9` and the remote is Artifactory `7.41.7`.

**Comment by zawlin** [comment]
> @zawlin Hello, I'm looking to deploying a very similar setup.
> 
> Do you have any feedback about the approach suggested by memsharded if you did go through with it?
> 
> Kind regards

Unfortunately we did not go through with it fully.  We simply test it during build stage and let it fail there. As we still have the testing package that was still tested in multiple platforms, it was deemed acceptable enough.  The basic idea however did work in a small project we tested. It's just that there's quite a few internal libraries we have to convert. 

One thing though is to handle the rpath issues, we mandate that all the ".so" files can only have rpaths that is either "$ORIGIN" or "$ORIGIN/lib" instead of using venv. For linking, we use a custom cmake generator which can inject the correct paths into the build chain. When we want to deploy the final "app"(i.e, final executable that can run), we again use cmake (which has the knowledge of where to find the libraries in conan due to custom generator) to recursively copy the so files into "lib" folder. Some libraries will have exceptions due to use of `dl_open`. For those cases we define regex-based file copy function in cmake to directly copy "so" files that cannot be traced. This way, there's a small advantage of not depending too much on conan. 

@memsharded, good to know! Sounds like something we can really use! We have been dreading having to migrate to conan 2.0. This serves as extra motivation. That wall needs to be scaled eventually.

**Comment by memsharded** [comment]
@SpectreVert 

> ERROR: 500: org.jfrog.repomd.conan.exceptions.ConanInfoException: Missing section in conaninfo.txt. 

This typically means you need to update your Artifactory version (to 7.53 at least IIRC) to support Conan 2.0 fully

**Comment by memsharded** [comment]
@zawlin 

> @memsharded, good to know! Sounds like something we can really use! We have been dreading having to migrate to conan 2.0. This serves as extra motivation. That wall needs to be scaled eventually.

And that is only the beginning of 2.0 🙂 We are also about to launch the "backup-sources" feature, that is also fantastic, and things like custom commands or the new lockfiles are really game-changing, so I hope the new things make the effort of migration to 2.0 worth it.
